modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="mls"
version="1.0"
displayName="mls"
description=""
authors="enjarai"
[[dependencies.mls]]
   modId="forge"
   mandatory=true
   versionRange="[47,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.mls]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20.1,1.21)"
   ordering="NONE"
   side="BOTH"
